### ISSUE TITLE
windows下operation.go中的 Runes()出现死锁bug

### ISSUE THREAD

**Issue by JoeeeeeeeyLee** [mritd/promptx#4]
我的代码
```go
cfg := &promptx.SelectConfig{
		ActiveTpl:    "» {{ .Type | cyan }} ({{ .ENDescription | cyan }})",
		InactiveTpl:  " {{ .Type | white }} ({{ .ENDescription | white }})",
		SelectPrompt: "Commit Type",
		SelectedTpl:  "{{ \"» \" | green }}{{\"Type:\" | cyan }} {{ .Type }}",
		DisPlaySize:  9,
		DetailsTpl: `
--------- Commit Type ----------
{{ "Type:" | faint }}	{{ .Type }}
{{ "Description:" | faint }}	{{ .ZHDescription }}({{ .ENDescription }})`,
	}

	s := &promptx.Select{
		Config: cfg,
		Items:  commitTypes,
	}

	idx := s.Run()

	if commitTypes[idx].Type == EXIT {
		fmt.Println("Talk is cheap. Show me the code.")
		os.Exit(0)
	}

	return commitTypes[idx].Type
```
报错信息
```bash
goroutine 1 [select]:
github.com/mritd/readline.(*Operation).Runes(0xc0001441c0, 0x0, 0x0, 0x0, 0x0, 0x0)
       go/pkg/mod/github.com/mritd/readline@v0.0.0-20190430155141-1af16399dc52/operation.go:390 +0x1c5
github.com/mritd/readline.(*Operation).String(...)
       go/pkg/mod/github.com/mritd/readline@v0.0.0-20190430155141-1af16399dc52/operation.go:375
github.com/mritd/readline.(*Instance).Readline(0xc00010a420, 0x0, 0x289, 0x30b, 0x289)
        /go/pkg/mod/github.com/mritd/readline@v0.0.0-20190430155141-1af16399dc52/readline.go:256 +0x36
github.com/mritd/promptx.(*Select).Run(0xc000214100, 0x0)
        /go/pkg/mod/github.com/mritd/promptx@v0.0.0-20190919142911-51b6aa75496f/select.go:218 +0x2cb
/git.SelectCommitType(0x2d2b80, 0xc000222000)
       /Downloads/workspace/git-toolkit/git/ci.go:68 +0x15d
/cmd.NewCi.func2(0xc0000a2840, 0x4b3e78, 0x0, 0x0)
       /Downloads/workspace/git-toolkit/cmd/ci.go:72 +0x21a
```
提示报错的地方
```go
func run(){
// read
    _, err = l.Readline()
    utils.CheckAndExit(err)
}

func (i *Instance) Readline() (string, error) {
	return i.Operation.String()
}

func (o *Operation) String() (string, error) {
	r, err := o.Runes()
	return string(r), err
}

func (o *Operation) Runes() ([]rune, error) {
	o.t.EnterRawMode()
	defer o.t.ExitRawMode()

	listener := o.GetConfig().Listener
	if listener != nil {
		listener.OnChange(nil, 0, 0)
	}

	o.buf.Refresh(nil) // print prompt
	o.t.KickRead()
        // 最终报错的地方
	select {
	case r := <-o.outchan:
		return r, nil
	case err := <-o.errchan:
		if e, ok := err.(*InterruptError); ok {
			return e.Line, ErrInterrupt
		}
		return nil, err
	}
        // 到这里截至
}
```
我利用了您提供的包写了一个规范commit提交的工具，并且通过gox生成linux macos windows版本的工具，但是只有在windows中运行时会提示我死锁，这种情况下有什么好的解决办法么

**Comment by mritd** [comment]
promptx 已经重写，你可以试试 https://github.com/mritd/bubbles
